import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
  paragraph: 'mb-2 text-gray-900',
  quote: 'border-l-4 border-gray-300 pl-4 italic my-4',
  heading: {
    h1: 'text-4xl font-bold mb-4 mt-6',
    h2: 'text-3xl font-bold mb-3 mt-5',
    h3: 'text-2xl font-bold mb-2 mt-4',
    h4: 'text-xl font-bold mb-2 mt-3',
    h5: 'text-lg font-bold mb-1 mt-2',
    h6: 'text-base font-bold mb-1 mt-2',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'list-decimal list-inside my-2',
    ul: 'list-disc list-inside my-2',
    listitem: 'ml-4 mb-1',
  },
  image: 'max-w-full h-auto',
  link: 'text-blue-600 hover:text-blue-800 underline cursor-pointer',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-gray-100 px-1 py-0.5 rounded text-sm font-mono',
  },
  code: 'bg-gray-100 font-mono text-sm p-2 rounded block my-2',
  codeHighlight: {
    atrule: 'text-purple-600',
    attr: 'text-blue-600',
    boolean: 'text-orange-600',
    builtin: 'text-purple-600',
    cdata: 'text-gray-600',
    char: 'text-green-600',
    class: 'text-orange-600',
    'class-name': 'text-orange-600',
    comment: 'text-gray-500 italic',
    constant: 'text-orange-600',
    deleted: 'text-red-600',
    doctype: 'text-gray-600 italic',
    entity: 'text-orange-600',
    function: 'text-blue-600',
    important: 'text-red-600',
    inserted: 'text-green-600',
    keyword: 'text-purple-600',
    namespace: 'text-orange-600',
    number: 'text-orange-600',
    operator: 'text-gray-700',
    prolog: 'text-gray-600 italic',
    property: 'text-blue-600',
    punctuation: 'text-gray-700',
    regex: 'text-green-600',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-orange-600',
    tag: 'text-blue-600',
    url: 'text-blue-600 underline',
    variable: 'text-orange-600',
  },
};

export default theme;
