apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-staging-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
    - name: image-name
      type: string
    - name: image-tag
      type: string
      default: "latest"
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
    - name: build
      taskRef:
        name: go-build
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image
          value: "$(params.image-name):$(params.image-tag)"
    - name: test
      taskRef:
        name: go-test
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: security-scan
      taskRef:
        name: security-scan
      runAfter:
        - build
      params:
        - name: image
          value: "$(params.image-name):$(params.image-tag)"
    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - test
        - security-scan
      workspaces:
        - name: source
          workspace: shared-workspace
