SHELL := /bin/bash

.PHONY: all plan apply destroy

all: plan

plan:
	@echo "Running terraform plan..."
	terraform plan

apply:
	@echo "Running terraform apply..."
	terraform apply

destroy:
	@echo "Running terraform destroy..."
	terraform destroy
